name: FEC Data Build

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * 1"  # Mondays 09:00 UTC — adjust as you like

permissions:
  contents: write  # needed to commit back

jobs:
  build-fec-data:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build members.csv
        run: npm run build:members

      - name: Commit updated members.csv
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(data): update config/members.csv from congress-legislators"
          file_pattern: config/members.csv
