name: FEC Data Build

on:
  workflow_dispatch:
  schedule:
    - cron: "17 7 * * 1,4"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install deps
        run: npm ci || npm i

      - name: Build financials
        env:
          FEC_API_KEY: ${{ secrets.FEC_API_KEY }}
        run: npm run build:financials

      - name: Commit data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/*.json
          git commit -m "data: refresh $(date -u +'%Y-%m-%dT%H:%MZ')" || echo "no changes"
          git push
