name: FEC Nightly Ingest

on:
  schedule:
    - cron: "20 9 * * *"     # 09:20 UTC daily
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  ingest:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: fec-nightly-subfolder/fec-nightly
    steps:
      - uses: actions/checkout@v4

      - name: Ensure folders
        run: mkdir -p data/raw data/warehouse

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests beautifulsoup4

      - name: Download latest FEC cn/cm
        run: |
          python scripts/download_latest_fec.py

      - name: Normalize to warehouse CSVs
        run: |
          python scripts/normalize_dim_tables.py
          ls -l data/warehouse || true

      - name: Commit warehouse updates
        run: |
          set -euo pipefail
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add data/warehouse/*.csv || true
          git commit -m "ci(fec): update warehouse outputs" || echo "no changes"
          git push
