name: FEC Nightly Ingest

on:
  schedule:
    - cron: "20 09 * * *"
  workflow_dispatch:

jobs:
  ingest:
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/ingest-core.yml   # points to your ingest logic
