name: FEC Nightly Ingest
on:
  schedule:
    # 09:20 UTC daily (02:20 Pacific)
    - cron: "20 09 * * *"
  workflow_dispatch: {}
permissions:
  contents: write

jobs:
  ingest:
    runs-on: ubuntu-latest
    concurrency:
      group: fec-nightly
      cancel-in-progress: false
    env:
      FEC_API_KEY: ${{ secrets.FEC_API_KEY }}
      NODE_ENV: production
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Ingest FEC raw -> warehouse -> site bundles
        run: |
          npm run build:data

      - name: Commit data updates
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "ci(fec): nightly data refresh"
          file_pattern: |
            data/raw/**
            data/warehouse/**
            data/site/**
