name: FEC Data Build

on:
  push:
    branches: [ "main" ]
    paths:
      - "scripts/**"
      - "config/**"
      - ".github/workflows/fec-build.yml"
      - "package.json"
      - "package-lock.json"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci || npm i

      - name: Build JSON
        run: npm run build:data || true

      - name: Commit data if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A data
          git diff --quiet || (git commit -m "chore(data): refresh JSON" && git push)
