name: Deploy static site to Pages

on:
  push:
    branches: ["main"]
    # Only redeploy when actual site files change (skip data-only updates)
    paths:
      - "**/*.html"
      - "**/*.css"
      - "**/*.js"
      - "images/**"
      - "assets/**"
      - "!assets/data/**"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: actions/configure-pages@v5
      # If you have a build step (npm/hugo/etc.), add it here
      - uses: actions/upload-pages-artifact@v3
        with:
          path: "."   # change to your build output dir if you build (e.g., "dist")

  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
