name: Deploy GitHub Pages

on:
  push:
    branches: [ main ]
    paths:
      - 'index.html'
      - 'Bills/**'
      - 'accountability/**'
      - 'assets/**'
      - 'styles.css'
      - 'data/**'
      - 'scripts/**'
      - 'package.json'
      - 'package-lock.json'
      - 'CNAME'
      - '.nojekyll'
      - '.github/workflows/*.yml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Configure Pages (no inputs)
      - uses: actions/configure-pages@v5

      # Build data (optional)
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: |
          if [ -f package-lock.json ]; then npm ci; else npm i; fi

      - name: Build data (writes JSON to ./data)
        env:
          FEC_API_KEY: ${{ secrets.FEC_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          npm run build:data

      # Assemble static site
      - name: Assemble site
        run: |
          set -euo pipefail
          rm -rf _site
          mkdir -p _site
          # copy only what the site needs
          rsync -a \
            --exclude ".git" \
            --exclude "node_modules" \
            --exclude "_site" \
            --exclude ".github" \
            ./ _site/
          # ensure Pages serves without Jekyll
          touch _site/.nojekyll

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
