name: Update FEC data

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

permissions:
  contents: write   # <-- needed to push

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0           # allow pushing
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install requests

      - name: Run updater
        env:
          FEC_API_KEY: ${{ secrets.FEC_API_KEY }}
          CANDIDATE_ID: ${{ secrets.CANDIDATE_ID }}
        run: python scripts/update_fec_data.py

      - name: Commit changes (if any)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add assets/data/strickland_funding.csv
          if git diff --staged --quiet; then
            echo "No changes"; exit 0
          fi
          git pull --rebase
          git commit -m "chore(data): refresh FEC totals"
          git push
