name: Update Congress Members Mirror

on:
  # Run weekly (Sundays 04:00 UTC). Adjust as you like.
  schedule:
    - cron: "0 4 * * SUN"
  # Allow manual runs from the Actions tab
  workflow_dispatch: {}

permissions:
  contents: write   # needed to commit the updated file

concurrency:
  group: mirror-members
  cancel-in-progress: false

jobs:
  mirror:
    runs-on: ubuntu-latest
    env:
      SOURCE_URL: https://raw.githubusercontent.com/unitedstates/congress-legislators/gh-pages/legislators-current.json
      TARGET_DIR: accountability/data
      TARGET_FILE: accountability/data/members.json
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Ensure data directory exists
        run: mkdir -p "${TARGET_DIR}"

      - name: Fetch latest legislators-current.json
        run: |
          set -euo pipefail
          # Try curl, fallback to wget
          if command -v curl >/dev/null 2>&1; then
            curl -fsSL "$SOURCE_URL" -o "$TARGET_FILE.raw"
          else
            wget -qO "$TARGET_FILE.raw" "$SOURCE_URL"
          fi

      - name: Validate & pretty-print JSON (jq)
        run: |
          set -euo pipefail
          # Validate JSON and pretty print
          jq . "$TARGET_FILE.raw" > "$TARGET_FILE"
          # quick sanity check: ensure it's a non-empty array
          test "$(jq 'length' "$TARGET_FILE")" -gt 0

      - name: Cleanup temp file
        run: rm -f "$TARGET_FILE.raw"

      - name: Commit changes if any
        run: |
          set -euo pipefail
          if git status --porcelain "$TARGET_FILE" | grep -q .; then
            git config user.name "GitHub Action"
            git config user.email "actions@github.com"
            git add "$TARGET_FILE"
            git commit -m "chore(data): update members.json ($(date -u +'%Y-%m-%d %H:%M:%S') UTC)"
            git push
          else
            echo "No changes to commit."
          fi
